# Configure Grafana with a LoadBalancer
grafana:
  service:
    type: LoadBalancer
    port: 80
    targetPort: 3000
    # Configure Prometheus with a LoadBalancer

prometheus:
  service:
    type: LoadBalancer
    port: 90
    targetPort: 9090