apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
spec:
  selector:
    app: prometheus-server
  type: NodePort # Exposes Prometheus externally
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30000 # Access via <Node-IP>:30000

###
#kubectl port-forward svc/prometheus-service 9090:80 -n monitoring
#Connect Data Source: In Grafana, add a new "Prometheus" 
#data source and set the URL to http://prometheus-service:80 
#(internal cluster DNS)
###